version: '3.8'

services:
  web:
    container_name: jiaezzang.osb.im
    image: jiaezzang.osb.im:1.${BUILD_NUMBER}
    restart: always
    ports:
      - 19010:80
    networks:
      - npm

networks:
  npm:
    external:
      name: npm
